Expandable input fixes
Zingle/ios-sdk pull request #308
Opened 2022-01-27 14:16 UTC by ruslan-maley

2022-01-27 18:34 UTC, jneel-medallia requested changes
What ticket is this fix for?

2022-01-27 18:34 UTC, jneel-medallia commented on Pod/Classes/UI/Controllers/ZNGConversationViewController.m
> +        if (object == self.inputToolbar.contentView.textView
Why is this happening here? The `if (context != ZNGConversationKVOContext)` clause was to escape without handling notifications that belong to other classes.

2022-01-28 10:34 UTC, ruslan-maley commented
> What ticket is this fix for?

https://jira.medallia.com/browse/ZIN-310

2022-01-28 15:33 UTC, ruslan-maley commented on Pod/Classes/UI/Controllers/ZNGConversationViewController.m
> +        if (object == self.inputToolbar.contentView.textView
@jneel-medallia This fix is related to wrong input toolbar size having more then 1 line of text. The code for counting it is implemented inside observeValueForKeyPath method in JSQMessagesViewController class. So it cannot be modified. If you have any ideas how it can be solved in another way, please let me know.

2022-01-28 19:51 UTC, jneel-medallia commented on Pod/Classes/UI/Controllers/ZNGConversationViewController.m
> +        if (object == self.inputToolbar.contentView.textView
We forked JSQMessagesViewController ourselves to address a problem in that library before. We could make a change there if it makes sense. If it's addressing a shortcoming in JSQ, that makes sense. If this is just an ugly fix to make our own stuff work, that's probably not great either.

Doing anything meaningful inside that `if (context != ZNGConversationKVOContext)` is confusing/misleading at best, so I really don't like that.

2022-01-28 19:53 UTC, jneel-medallia commented on Pod/Classes/UI/Controllers/ZNGConversationViewController.m
> +        if (object == self.inputToolbar.contentView.textView
To be clear, I'm not totally against an ugly fix, but something like that should at least have a comment explaining what it's doing and why.

2022-02-01 00:33 UTC, jneel-medallia approved these changes
I like the latest change much better. Thanks!

2022-02-01 09:33 UTC, merged